-- -----------------------------
-- Prueba para GitHub
-- -----------------------------
-- MySQL Script generated by MySQL Workbench
-- Sat Aug 28 16:20:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Bicicleta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bicicleta` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Bicicleta` (
  `BiciIndeCompraId` VARCHAR(45) NOT NULL,
  `NomFabricante` VARCHAR(16) NOT NULL,
  `PrecioUnitario` INT NULL,
  `AñoConstrucción` DATETIME NOT NULL,
  PRIMARY KEY (`BiciIndeCompraId`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Clientes EcoDosRuedas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clientes EcoDosRuedas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes EcoDosRuedas` (
  `AliasCliente` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  `Apellido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Celular` INT NULL DEFAULT CURRENT_TIMESTAMP,
  `Contraseña` INT NULL,
  `FechaNacimiento` DATETIME NULL,
  `IntenciónCompra_Registro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AliasCliente`, `IntenciónCompra_Registro`),
  CONSTRAINT `fk_Clientes EcoDosRuedas_IntenciónCompra1`
    FOREIGN KEY (`IntenciónCompra_Registro`)
    REFERENCES `mydb`.`IntenciónCompra` (`Registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_Clientes EcoDosRuedas_IntenciónCompra1_idx` ON `mydb`.`Clientes EcoDosRuedas` (`IntenciónCompra_Registro` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`IntenciónCompra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`IntenciónCompra` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`IntenciónCompra` (
  `Registro` VARCHAR(45) GENERATED ALWAYS AS (),
  `AliasCliente` VARCHAR(16) NULL,
  `ProductoDeInterés` VARCHAR(25) NULL,
  `Bicicleta_BiciIndeCompraId` VARCHAR(45) NULL,
  `Motocicleta_MotoIntDeCompraId` VARCHAR(45) NULL,
  PRIMARY KEY (`Registro`),
  CONSTRAINT `fk_IntenciónCompra_Bicicleta1`
    FOREIGN KEY (`Bicicleta_BiciIndeCompraId`)
    REFERENCES `mydb`.`Bicicleta` (`BiciIndeCompraId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IntenciónCompra_Motocicleta1`
    FOREIGN KEY (`Motocicleta_MotoIntDeCompraId`)
    REFERENCES `mydb`.`Motocicleta` (`MotoIntDeCompraId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_IntenciónCompra_Bicicleta1_idx` ON `mydb`.`IntenciónCompra` (`Bicicleta_BiciIndeCompraId` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_IntenciónCompra_Motocicleta1_idx` ON `mydb`.`IntenciónCompra` (`Motocicleta_MotoIntDeCompraId` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Motocicleta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Motocicleta` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Motocicleta` (
  `MotoIntDeCompraId` VARCHAR(45) NOT NULL,
  `NomFabricante` VARCHAR(16) NOT NULL,
  `PrecioUnitario` VARCHAR(40) NULL,
  `AutonomíaBatería` VARCHAR(32) NOT NULL,
  `Proveedor Motor Eléctrico_Id` INT NOT NULL,
  PRIMARY KEY (`MotoIntDeCompraId`, `Proveedor Motor Eléctrico_Id`),
  CONSTRAINT `fk_Motocicleta_Proveedor Motor Eléctrico1`
    FOREIGN KEY (`Proveedor Motor Eléctrico_Id`)
    REFERENCES `mydb`.`Proveedor Motor Eléctrico` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_Motocicleta_Proveedor Motor Eléctrico1_idx` ON `mydb`.`Motocicleta` (`Proveedor Motor Eléctrico_Id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Proveedor Motor Eléctrico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Proveedor Motor Eléctrico` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor Motor Eléctrico` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(16) NOT NULL,
  `Dirección` VARCHAR(255) NULL,
  `Teléfono` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`Id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`timestamps` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
